apiVersion: v1
kind: Service
metadata:
  name: grafana-rest
  labels:
    app: grafana
    chart: {{ template "grafana.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app: grafana-server
  ports:
    - port: 3000
      targetPort: 3000
