apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clusterid }}-nodeport-rest
spec:
  type: NodePort
  ports:
  - name: rest
    port: 8081
    targetPort: 8081
    {{- if (not (empty .Values.nodePort)) }}
    nodePort: {{ .Values.nodePort }}
    {{- end }}
  selector:
    app: {{ .Values.clusterid }}
    component: jobmanager
