apiVersion: v1
kind: Service
metadata:
  name: redis-external
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      {{- if (not (empty .Values.nodePort)) }}
      nodePort: {{ .Values.nodePort }}
      {{- end }}
  selector:
    app: redis
