apiVersion: v1
kind: Service
metadata:
 name: prometheus-rest
 annotations:
   prometheus.io/scrape: 'true'
   prometheus.io/port:   '9999'
spec:
 type: NodePort
 selector:
   app: prometheus
 ports:
   - port: 9090
     targetPort: 9090
