apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.service.labels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.service.labels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.service.annotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.service.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- if not (empty .Values.service.loadBalancerIP) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if .Values.service.externalIPs }}
  externalIPs: {{- toYaml .Values.service.externalIPs | nindent 4 }}
  {{- end }}
  ports:
    {{- if (not (and (eq .Values.service.type "NodePort") (.Values.auth.tls.disableNonTlsNodePorts))) }}
    - name: amqp
      port: {{ .Values.service.port }}
      targetPort: amqp
      {{- if (eq .Values.service.type "ClusterIP") }}
      nodePort: null
      {{- else if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.amqpNodePort)) }}
      nodePort: {{ .Values.service.amqpNodePort }}
      {{- end }}
    {{- end }}
    {{- if .Values.auth.tls.enabled }}
    - name: amqp-ssl
      port: {{ .Values.service.tlsPort }}
      targetPort: amqp-ssl
      {{- if (eq .Values.service.type "ClusterIP") }}
      nodePort: null
      {{- else if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.amqpTlsNodePort)) }}
      nodePort: {{ .Values.service.amqpTlsNodePort }}
      {{- end }}
    {{- end }}
    {{- if (not (and (eq .Values.service.type "NodePort") (.Values.auth.tls.disableNonTlsNodePorts))) }}
    - name: mqtt
      port: {{ .Values.service.mqttPort }}
      targetPort: mqtt
      {{- if (eq .Values.service.type "ClusterIP") }}
      nodePort: null
      {{- else if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.mqttNodePort)) }}
      nodePort: {{ .Values.service.mqttNodePort }}
      {{- end }}
    {{- end }}
    {{- if .Values.auth.tls.enabled }}
    - name: mqtt-ssl
      port: {{ .Values.service.mqttTlsPort }}
      targetPort: mqtt-ssl
      {{- if (eq .Values.service.type "ClusterIP") }}
      nodePort: null
      {{- else if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.mqttTlsNodePort)) }}
      nodePort: {{ .Values.service.mqttTlsNodePort }}
      {{- end }}
    {{- end }}
    - name: epmd
      port: 4369
      targetPort: epmd
      {{- if (eq .Values.service.type "ClusterIP") }}
      nodePort: null
      {{- else if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.epmdNodePort))) }}
      nodePort: {{ .Values.service.epmdNodePort }}
      {{- end }}
    - name: dist
      port: {{ .Values.service.distPort }}
      targetPort: dist
      {{- if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- else if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.distNodePort))) }}
      nodePort: {{ .Values.service.distNodePort }}
      {{- end }}
    - name: http-stats
      port: {{ .Values.service.managerPort }}
      targetPort: stats
      {{- if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- else if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.managerNodePort))) }}
      nodePort: {{ .Values.service.managerNodePort }}
      {{- end }}
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      {{- if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- else if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.metricsNodePort))) }}
      nodePort: {{ .Values.service.metricsNodePort }}
      {{- end }}
    {{- end }}
    {{- if .Values.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  selector: {{ include "common.labels.matchLabels" . | nindent 4 }}
